name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Trigger Render Deployment
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
        https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/jobs